# GoReleaser configuration
# Documentation: https://goreleaser.com

version: 2

before:
  hooks:
    # Ensure dependencies are up to date
    - go mod tidy
    # Run tests before building
    - go test ./...

builds:
  - id: marinatemd
    main: ./cmd/marinate/main.go
    binary: marinate

    # Environments to build for
    env:
      - CGO_ENABLED=0

    goos:
      - linux
      - darwin
      - windows

    goarch:
      - amd64
      - arm64
      - arm

    goarm:
      - "7"

    # Ignore specific combinations
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64

    # Build flags
    flags:
      - -trimpath

    ldflags:
      - -s -w
      - -X github.com/glueckkanja/marinatemd/cmd/marinatemd.Version={{.Version}}
      - -X github.com/glueckkanja/marinatemd/cmd/marinatemd.Commit={{.Commit}}
      - -X github.com/glueckkanja/marinatemd/cmd/marinatemd.BuildDate={{.Date}}

archives:
  - id: marinatemd-archive
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{ .Arch }}

    files:
      - README.md

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - Merge pull request
      - Merge branch
  groups:
    - title: "Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Performance Improvements"
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "Refactors"
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: "Other Changes"
      order: 999

# GitHub release configuration
release:
  github:
    owner: glueckkanja
    name: marinatemd

  # Create a draft release for manual review
  draft: false

  # Mark as prerelease
  prerelease: auto

  # Make archives available in GitHub releases
  make_latest: true

  # Release name template
  name_template: "Release {{.Version}}"

  # Header and footer for release notes
  header: |
    ## MarinateMD {{.Version}}

    Release of MarinateMD - Terraform/OpenTofu variable documentation tool.

  footer: |
    ## Installation

    ### Using Go
    ```bash
    go install github.com/glueckkanja/marinatemd/cmd/marinate@{{.Version}}
    ```

    ### Download Binary
    Download the appropriate binary for your platform from the assets below.

# Homebrew tap (optional - uncomment if you want to publish to Homebrew)
# brews:
#   - name: marinatemd
#     repository:
#       owner: glueckkanja
#       name: homebrew-tap
#     folder: Formula
#     homepage: https://github.com/glueckkanja/marinatemd
#     description: "Terraform/OpenTofu variable documentation tool"
#     license: MIT
#     install: |
#       bin.install "marinatemd"

# Docker images (optional)
# dockers:
#   - image_templates:
#       - "ghcr.io/glueckkanja/marinatemd:{{ .Version }}"
#       - "ghcr.io/glueckkanja/marinatemd:latest"
#     dockerfile: Dockerfile
#     build_flag_templates:
#       - "--pull"
#       - "--label=org.opencontainers.image.created={{.Date}}"
#       - "--label=org.opencontainers.image.title={{.ProjectName}}"
#       - "--label=org.opencontainers.image.revision={{.FullCommit}}"
#       - "--label=org.opencontainers.image.version={{.Version}}"
#     extra_files:
#       - README.md
#       - LICENSE
