export_path: "docs"
docs_file: "README.md"

markdown_template:
  attribute_template: "{attribute} - ({required}) {description}"
  required_text: "Required"
  optional_text: "Optional"
  escape_mode: "inline_code"
  indent_style: "bullets"
  indent_size: 2
  object_separators:
    - level: 1
      style: "line"
    - level: 2
      style: "line"

split:
  output_dir: "split_simple"
  header_file: "_header.md"
  footer_file: "_footer.md"
