export_path: "docs"
docs_file: "README.md"

markdown_template:
  attribute_template: "{attribute} - ({required}) {description}"
  required_text: "Required"
  optional_text: "Optional"
  escape_mode: "inline_code"
  indent_style: "bullets"
  indent_size: 2
  separator_indents: [] # No separators
